export const LANGUAGE = {
  en: {
    title: "About us",
    desc: "ABC is at the forefront of revolutionizing the customer relationship management (CRM) industry through cutting-edge artificial intelligence (AI) solutions. We are a team of forward-thinking innovators dedicated to transforming how businesses interact with their customers. By leveraging the latest advancements in AI, we aim to streamline and enhance CRM processes, making them more efficient, personalized, and responsive to the needs of modern enterprises. Our commitment to excellence drives us to continuously push the boundaries of what’s possible, ensuring that our clients stay ahead in a rapidly evolving digital landscape.",
    title1: "Mission",
    desc1: "At ABC, our mission is to empower businesses with AI-driven CRM solutions that are not only advanced but also intuitive and user-friendly. We believe that modern CRM should be more than just a tool—it should be a seamless experience that fosters stronger, more meaningful customer relationships. Our goal is to provide solutions that simplify complex processes, enabling businesses to focus on what truly matters: their customers. By staying true to our core values of innovation, adaptability, and customer-centricity, we strive to redefine the future of CRM, one AI-driven solution at a time.",
  },
  hi: {
    title: "के बारे में",
    desc: "एबीसी अत्याधुनिक कृत्रिम बुद्धिमत्ता (एआई) समाधानों के माध्यम से ग्राहक संबंध प्रबंधन (सीआरएम) उद्योग में क्रांति लाने में सबसे आगे है। हम दूरदर्शी नवप्रवर्तकों की एक टीम हैं जो व्यवसायों के अपने ग्राहकों के साथ बातचीत करने के तरीके को बदलने के लिए समर्पित हैं। एआई में नवीनतम प्रगति का लाभ उठाकर, हमारा लक्ष्य सीआरएम प्रक्रियाओं को सुव्यवस्थित और बढ़ाना है, जिससे उन्हें आधुनिक उद्यमों की जरूरतों के लिए अधिक कुशल, वैयक्तिकृत और उत्तरदायी बनाया जा सके। उत्कृष्टता के प्रति हमारी प्रतिबद्धता हमें लगातार संभव सीमाओं को आगे बढ़ाने के लिए प्रेरित करती है, जिससे यह सुनिश्चित होता है कि हमारे ग्राहक तेजी से विकसित हो रहे डिजिटल परिदृश्य में आगे रहें।",
    title1: "उद्देश्य",
    desc1: "एबीसी में, हमारा मिशन एआई-संचालित सीआरएम समाधानों के साथ व्यवसायों को सशक्त बनाना है जो न केवल उन्नत हैं बल्कि सहज और उपयोगकर्ता के अनुकूल भी हैं। हमारा मानना ​​है कि आधुनिक सीआरएम सिर्फ एक उपकरण से कहीं अधिक होना चाहिए - यह एक सहज अनुभव होना चाहिए जो मजबूत, अधिक सार्थक ग्राहक संबंधों को बढ़ावा देता है। हमारा लक्ष्य ऐसे समाधान प्रदान करना है जो जटिल प्रक्रियाओं को सरल बनाते हैं, व्यवसायों को उस चीज़ पर ध्यान केंद्रित करने में सक्षम बनाते हैं जो वास्तव में मायने रखती है: उनके ग्राहक। नवाचार, अनुकूलनशीलता और ग्राहक-केंद्रितता के अपने मूल मूल्यों के प्रति सच्चे रहकर, हम एक समय में एक एआई-संचालित समाधान, सीआरएम के भविष्य को फिर से परिभाषित करने का प्रयास करते हैं।",
  },
  ru: {
    title: "О нас",
    desc: "ABC находится в авангарде революции в сфере управления взаимоотношениями с клиентами (CRM) с помощью передовых решений искусственного интеллекта (ИИ). Мы — команда дальновидных новаторов, стремящихся изменить способы взаимодействия бизнеса со своими клиентами. Используя последние достижения в области искусственного интеллекта, мы стремимся оптимизировать и совершенствовать процессы CRM, делая их более эффективными, персонализированными и отвечающими потребностям современных предприятий. Наше стремление к совершенству заставляет нас постоянно расширять границы возможного, гарантируя, что наши клиенты останутся впереди в быстро развивающейся цифровой среде.",
    title1: "Миссия",
    desc1: "Наша миссия в ABC — предоставить компаниям возможности CRM-решений на основе искусственного интеллекта, которые не только передовые, но также интуитивно понятные и удобные для пользователя. Мы считаем, что современное CRM должно быть больше, чем просто инструментом — это должен быть цельный опыт, способствующий более крепким и значимым отношениям с клиентами. Наша цель — предоставлять решения, которые упрощают сложные процессы, позволяя предприятиям сосредоточиться на том, что действительно важно: на своих клиентах. Оставаясь верными нашим основным ценностям инноваций, адаптивности и ориентации на клиента, мы стремимся переопределить будущее CRM, по одному решению на основе искусственного интеллекта за раз.",
  },
  sp: {
    title: "Sobre nosotros",
    desc: "ABC está a la vanguardia de la revolución de la industria de la gestión de relaciones con los clientes (CRM) a través de soluciones de inteligencia artificial (IA) de vanguardia. Somos un equipo de innovadores con visión de futuro dedicados a transformar la forma en que las empresas interactúan con sus clientes. Al aprovechar los últimos avances en IA, nuestro objetivo es optimizar y mejorar los procesos de CRM, haciéndolos más eficientes, personalizados y receptivos a las necesidades de las empresas modernas. Nuestro compromiso con la excelencia nos impulsa a superar continuamente los límites de lo posible, garantizando que nuestros clientes se mantengan a la vanguardia en un panorama digital en rápida evolución.",
    title1: "Misión",
    desc1: "En ABC, nuestra misión es brindar a las empresas soluciones CRM basadas en IA que no solo sean avanzadas sino también intuitivas y fáciles de usar. Creemos que el CRM moderno debería ser más que una simple herramienta: debería ser una experiencia fluida que fomente relaciones más sólidas y significativas con los clientes. Nuestro objetivo es brindar soluciones que simplifiquen procesos complejos, permitiendo a las empresas centrarse en lo que realmente importa: sus clientes. Manteniéndonos fieles a nuestros valores fundamentales de innovación, adaptabilidad y centrado en el cliente, nos esforzamos por redefinir el futuro de CRM, una solución impulsada por IA a la vez.",
  },
};
